spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2-console
      enabled: true
  sql:
    init:
      mode: embedded
      data-locations: classpath:db/data.sql